Version: ltb_hlju_1.0
# 调试模式，用于寻找错误出现的坐标，默认为false
# 特别提示：调试完成后请记得将debug改为false

debug: false

notifyOption:
    method: 1
    qywxOption:
        corpid: ''
        corpsecret: ''
        agentid: ''

users:
    - user:
        # 任务类型（收集：0、签到：1）
        type: 0
        # username 学号或者工号
        username: '' #这里填写你的学号
        # password 密码
        password: '' #这里填写你的密码，就是教务系统那个密码
        # address 地址，定位信息
        address: '黑龙江省哈尔滨市南岗区学府东四道街'
        notifyOption:
            method: 1
            # rcvAcc为接受消息的账号，可以为Email账号、QQ号、或者是企业微信ID(@all为全体)
            rcvAcc: ''
        # lon 经度
        lon: 126.636721
        # lat 纬度
        lat: 45.712265
        abnormalReason: ''
        # 是否检查表单的标题（1代表检查，0代表不检查）
        checkTitle: 1
        forms:
         - form:
             title: 在校状态
             value: 不在校
         - form:
             title: 不在校原因
             value: 其他(放假)      
         - form:
             ignore: 1
         - form:
             title: 不在校学生体温状况
             value: 正常     
         - form:
             title: 不在校学生隔离情况
             value: 未隔离                     
         - form:
             ignore: 1
         - form:
             ignore: 1
         - form:
             title: 14天内是否有中高风险地区旅居史
             value: 否
         - form:
             title: 14天内是否有中高风险地区所在区（县）旅居史
             value: 否     
         - form:
             ignore: 1
         - form:
             title: 不在校学生安全承诺
             value: 本人承诺遵守学校及属地防疫规定，并做到未经审批不私自返校，如有特殊情况主动向辅导员老师报备
